routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



/*Route::match(['get','post'],'/',function(){
	$nit = Input::get('email');
	$name = Input::get('name');
	$pais = Input::get('pais');
	$registro = Input::get('registro');
 return view('proveedor',['nit'=>$nit,'pais'=>$pais,'name'=>$name, 'registro'=>$registro]);
});*/

Auth::routes();
Route::get('/', 'News@mostrar');

Route::get('/home', 'HomeController@index');

Route::get('/author','Authors@index');

//Adquirir todos los metodos que estan en el controlador Authors y convertirlos en Ruta.
Route::resource('/authors', 'Authors');

//Adquirir todos los metodos que estan en el controlador News y convertirlos en Ruta.
Route::resource('/news', 'News');

//Obetener el autor de en la vista de Noticias

Route::get('/api/news','News@authors');

//listado de las noticias
Route::get('/api/list','News@listanoticia');

//Add comment
Route::post('/add/comment','CommentController@addcomment');

app/Http/Controllers/News.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Author;
use App\Notice;
use App\Comment;
use Storage;

class News extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         return view('news.news');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'title' => 'required',
            'description' => 'required',
            'urlImg' => 'image|required',
            ]);
        $news = new Notice;
        $news->title = $request->title;
        $news->description = $request->description;
        $news->authors_id= $request->authors;
        $img= $request->file('urlImg');
        $file_route=time().'_'.$img->getClientOriginalName();
        //Con esta instrucción guardamos la imagen en el Disco que se creo en config/File System
        Storage::disk('imgNoticias')->put($file_route, file_get_contents( $img->getRealPath() ) );
        $news->urlImg=$file_route;
        if ($news->save()){
            return back()->with('msj','Datos Guardados');
        }else{
            return back()->with('errormsj','Los datos no se guardaron');;
        }
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $notice = Notice::find($id);
        return view('news.edit')->with(['edit'=>'true','notice'=>$notice]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'title' => 'required',
            'description' => 'required',
            'urlImg' => 'image|required',
            ]);
        $news = Notice::find($id);
        $news->title = $request->title;
        $news->description = $request->description;
        $news->authors_id= $request->authors;
        $img= $request->file('urlImg');
        $file_route=time().'_'.$img->getClientOriginalName();
        //Con esta instrucción guardamos la imagen en el Disco que se creo en config/File System
        Storage::disk('imgNoticias')->put($file_route, file_get_contents( $img->getRealPath() ) );
        Storage::disk('imgNoticias')->delete($request->img);
        $news->urlImg=$file_route;
        if ($news->save()){
            $notice= Notice::all();
            return view('news.list')->with(['notice' => $notice]);
        }else{
            return back()->with('errormsj','Los datos no se guardaron');;
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       Notice::destroy($id);
       return back();
    }

    //Mostrar las noticias
    public function mostrar()
    {
       $notice=Notice::all();
       $comment= Comment::all();
       $comment3=Comment::select('notices_id', 'name', 'text')->groupBy('notices_id','name','text')->take(6)->get();
      
       return view('welcome')->with(['notice' => $notice , 'comment' => $comment, 'comment3' => $comment3]);
    }
    //Fultra los autores ya registrados
    public function authors(Request $request){
        $term = $request->input('term') ?: '';
        $author = Author::where('name', 'like', '%'.$term.'%')->pluck('name', 'id');
        $data = [];
        foreach ($author as $id => $name) {
          $data[] = ['id' => $id, 'text' => $name];
        }
        return json_encode($data);
    }

    //list news
    public function listanoticia()
    {
        $notice= Notice::all();
        return view('news.list')->with(['notice' => $notice]);
    }
}

resources/views/news/edit.blade.php
@extends('layouts.app')

@section('content')
@section('css')
<link href="/css/main.css" rel="stylesheet">
<link rel="stylesheet" href="/css/select2.min.css" />
@endsection
@if(isset($notice))
<div class="container">
    <div class="row">
    	<div class="col-md-8 col-md-offset-2">
	        <div class="panel-body">
	           	<form  role='form' method="POST" enctype="multipart/form-data" action= "{{ route('news.update', $notice->id)}} ">
	           	<input type="hidden" name="_method" value="PUT">
	           	<input  class="hide" type="text" name="img" value=" {{ '$notice->urlImg'}} ">
	           	{{ csrf_field() }}
				  	<h1>Registro de la Noticia</h1>
				  	<div class="inset">
				   	@if(session()->has('msj'))
	        			<div class="alert alert-success" role='alert'>{{ session('msj') }}</div>
			       	@endif
			        @if(session()->has('errormsj'))
	        			<div class="alert alert-success" role='alert'>Error al guardar los datos</div>
			       	@endif
				  	<p>
				    	<label for="title">Titulo</label>
				   		<input id="title" type="text" class="form-control" name="title" value="{{ $notice->title }}">
	                    @if ($errors->has('title'))
	                        <span style="color:red;">
	                            <strong>{{ $errors->first('title') }}</strong>
	                        </span>
	                    @endif
				  	</p>
				  	<p>
				    	<label for="description">Descripción</label>
				    	<textarea class="ckeditor" id="description" type="textarea" class="form-control" rows="6" cols="70" name="description" value="{{ old('description') }}">
	                    </textarea>
	                    @if ($errors->has('description'))
	                        <span style="color:red;">
	                            <strong>{{ $errors->first('description') }}</strong>
	                        </span>
	                    @endif
				  	</p>
				  	<p>
				  		<label class="form-label" for="authors">Autor de la Noticia</label>
          				<select name="authors" id="authors" class="form-control" ><option value="{{ $notice->authors_id }}"> {{ $notice->authors->name }}</option>
          				</select>
        				@if ($errors->has('authors'))
                         <span style="color:red;">
                            <strong>{{ $errors->first('authors') }}</strong>
                        	</span>
                    	@endif     
				  	</p>
				  	<p >
				    	<label for="urlImg" >Imagen</label>
				    	<input type=file size=60 name="urlImg" class="form-control"  id="urlImg"><br><br>
						@if ($errors->has('urlImg'))
	                         <span style="color:red;">
	                            <strong>{{ $errors->first('urlImg') }}</strong>
	                        </span>
	                    @endif
				  	</p>
				  	
				  
				  </div>
				  <p class="p-container">
				    
				    <button type="submit" class="btn btn-warning" >Modificar</button>
				  </p>
				</form>
	        </div>
    	</div>
	</div>
</div>
@endif
@endsection
@section('js')

	<script src="/js/select2.min.js"></script>	
 	<script src="/js/news/news.js"></script>

@endsection

resources/views/news/list.blade.php
@extends('layouts.app')

@section('content')

@section('css')
<link rel="stylesheet" href="/css/stacktable.css" />

@endsection
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Panel heading</div>
  <div class="col-md-8 col-md-offset-2">
  <!-- Table -->
  <table id='listnew' class='table stacktable' >
  	@if(isset($notice))
    <thead>
		<th>Titulo</th>
		<th>Descripción</th>
		<th>Autor</th>
		<th>Imagen</th>
		<th></th>
	</thead>
	<tbody>
	@foreach ($notice as $n)
		<tr>
			<td>{{ $n->title }}</td>
			<td><div>{!! $n->description !!}</div></td>
			<td>{{ $n->authors->name }}</td>
			<td><img src="/imgNoticias/{{ $n->urlImg }}" class="img-responsive"  width="100" height="100" alt="Responsive image"></td>
			<td>
				<a href="/news/{{ $n->id }}/edit" class="btn btn-warning btn-xs">Modificar</a>

				<form action="{{route('news.destroy',$n->id)}}" method="POST">
					<input type="hidden" name="_method" value="DELETE">
	           		{{ csrf_field() }}
	           		<input type='submit' class="btn btn-danger btn-xs" value="Eliminar"></input>
				</form>
				
			</td>
		</tr>
	@endforeach	
	</tbody>
	@endif	
		
  </table>
  </div>
</div>
</div>
@endsection
@section('js')

 	<script src="/js/news/stacktable.js"></script>
 	<script src="/js/news/list.js"></script>
@endsection

resources/views/news/news.blade.php
@extends('layouts.app')

@section('content')

@section('css')
<link href="/css/main.css" rel="stylesheet">
<link rel="stylesheet" href="/css/select2.min.css" />
@endsection
<div class="container">
    <div class="row">
    	<div class="col-md-8 col-md-offset-2">
	        <div class="panel-body">
	           	<form  role='form' method="POST" enctype="multipart/form-data" action={{url('news')}}>
	           	{{ csrf_field() }}
				  	<h1>Registro de la Noticia</h1>
				  	<div class="inset">
				   	@if(session()->has('msj'))
	        			<div class="alert alert-success" role='alert'>{{ session('msj') }}</div>
			       	@endif
			        @if(session()->has('errormsj'))
	        			<div class="alert alert-success" role='alert'>Error al guardar los datos</div>
			       	@endif
				  	<p>
				    	<label for="title">Titulo</label>
				   		<input id="title" type="text" class="form-control" name="title" value="{{ old('title')}}">
	                    @if ($errors->has('title'))
	                        <span style="color:red;">
	                            <strong>{{ $errors->first('title') }}</strong>
	                        </span>
	                    @endif
				  	</p>
				  	<p>
				    	<label for="description">Descripción</label>
				    	<textarea class="ckeditor" id="description" type="textarea" class="form-control" rows="6" cols="70" name="description" value="{{ old('description') }}">
	                    @if ($errors->has('description'))
	                        <span style="color:red;">
	                            <strong>{{ $errors->first('description') }}</strong>
	                        </span>
	                    @endif
	                    </textarea>
				  	</p>
				  	<p>
				  		<label class="form-label" for="authors">Autor de la Noticia</label>
          				<select name="authors" id="authors" class="form-control" >
            				@if ($errors->has('authors'))
	                         <span style="color:red;">
	                            <strong>{{ $errors->first('authors') }}</strong>
	                        	</span>
	                    	@endif     
          				</select>
				  	</p>
				  	<p >
				    	<label for="urlImg" >Imagen</label>
				    	<input type=file size=60 name="urlImg" class="form-control"  id="urlImg"><br><br>
						@if ($errors->has('urlImg'))
	                         <span style="color:red;">
	                            <strong>{{ $errors->first('urlImg') }}</strong>
	                        </span>
	                    @endif
				  	</p>
				  	
				  
				  </div>
				  <p class="p-container">
				    
				    <input type="submit" name="guardar" id="guardar" value="Guardar">
				  </p>
				</form>
	        </div>
    	</div>
	</div>
</div>
@endsection
@section('js')

	<script src="/js/select2.min.js"></script>	
 	<script src="/js/news/news.js"></script>

@endsection